# Generated by Django 5.0.7 on 2025-01-31 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_faq_question_as_faq_question_gu_faq_question_kn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='question_as',
        ),
    ]
